ansr1 = input ("name of a fat guy u knew in high school")
ansr2 = input ("sports team")
ansr3 = input ("name of a place u can get beef jurky")
ansr4 = input ("silly name for a strip club")
ansr5 = input ("a hair product")
ansr6 = input ("barn animal")
ansr7 = input ("name of annoying guy from high school")
ansr8 = input ("porn magazine")
ansr9 = input ("cheap haircut place")
ansr10 = input ("name of girl from high school")
ansr11 = input ("body part")
ansr12 = input ("cartoon character")
ansr13 = input ("a cable network")
ansr14 = input ("nasty smelling food")
ansr15 = input ("name of bald actor")
ansr16 = input ("a strippers name")
print(" ")
print(" ")
print("Dear Mr." + ansr1)
print(" ")
print("I'm leaving you. You've worn one too many " + ansr2, "hats.")
print("Every time you leave the house to go to " + ansr3, "or")
print(ansr4 + " you're covering me up. It's like you're embarrassed")
print("to be seen with me. When you're not covering me up with a hat, you just")
print("smother me with " + ansr5, "that smells like a " + ansr6)
print(" ")
print("You used to care about me. You'd go to " + ansr7,"'s barber")
print("shop. He had all those issues of " + ansr8, "in the waiting area. That was")
print("fun! But then, you started going to " + ansr9,". It's like you")
print("stopped caring.")
print(" ")
print("I suppose when " +ansr10, "broke up with you")
print("it was hard. She would run her " + ansr11, "through me. That was awesome.")
print("She even convinced you to stop shaving " + ansr12, "in to the side of")
print("your head. Once she was gone you were never the same. You sat around the")
print("house watching " + ansr13, "eating " + ansr14,",")
print("while covering me up.")
print(" ")
print("It's best that I move on. You might like being bald. I see a lots of dudes shave it")
print("all off anyway. Kinda makes'em look like " + ansr15,".")
print("It might help you score with " + ansr16,". Good luck.")
print(" ")
print("Sincerely,")
print("Your hair")